language: python
cache: pip
install:
  - pip install mkdocs
script:
  - mkdocs build --verbose --clean --strict
deploy:
  provider: nav
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: site
  edge: true
  on:
    branch: master