site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - fenced_code
    - sane_lists

pages:
  - Home: index.md
  - Bash: bash.md
  - Quest:
    - Introduction: quest-intro.md
    - Andersen-Lab-Env: quest-andersen-lab-env.md
    - Nextflow: quest-nextflow.md
    - Mounting Quest: quest-mount.md
  - Pipelines:
    - Overview: pipeline-overview.md
    - Adding Sequencing Data: adding-seq-data.md
    - Sample Sheets: sample-sheets.md
    - Trimming: pipeline-trimming.md
    - NIL / RIL: pipeline-nil-ril.md
    - Concordance: pipeline-concordance.md
    - WI: pipeline-wi.md
    - Cegwas: pipeline-cegwas.md
  - R: r.md
  - Backup: backup.md
  - Cloud: cloud.md
  - Andersen Labsite: labsite.md