site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - fenced_code
    - sane_lists

pages:
  - Home: index.md
  - Bash: bash.md
  - Quest:
    - Introduction: quest-intro.md
    - Setting up Nextflow: quest-nextflow.md
    - Mounting Quest: quest-mount.md
  - Nextflow: nextflow.md
  - Pipelines:
    - NIL: pipeline-nil.md
    - RIL: pipeline-ril.md
    - Concordance: pipeline-wi.md
    - WI: pipeline-wi.md
    - Trimming: pipeline-trimming.md
    - cegwas: pipeline-cegwas.md
  - R: r.md
  - Travis-CI: travis-ci.md
  - Google Cloud: google-cloud.md
  - CeNDR: cendr.md
  - Domains: domains.md
  - Andersen Labsite: labsite.md