site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
            permalink: true
            separator: _
    - fenced_code
    - sane_lists

nav:
    - Home: index.md
    - Bash: bash.md
    - Quest:
          - Introduction: quest-intro.md
          - Nextflow: quest-nextflow.md
          - Mounting Quest: quest-mount.md
    - Pipelines:
          - Overview: pipeline-overview.md
          - Adding NILs Sequencing Data: adding-seq-data.md
          - GCP configuration: pipeline-GCPconfig.md
          - Build docker iamge: pipeline-docker.md
          - Trimming: pipeline-trimming.md
          - NIL / RIL: pipeline-nil-ril.md
          - WI-Alignment: pipeline-alignment.md
          - WI-Concordance: pipeline-concordance.md
          - WI: pipeline-wi.md
          - Cegwas: pipeline-cegwas.md
    - CeNDR: cendr.md
    - R: r.md
    - Backup: backup.md
    - Cloud: cloud.md
    - Andersen Labsite: labsite.md
extra_css:
    - css/version-select.css
extra_javascript:
    - js/version-select.js
