site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
        permalink: True
    - fenced_code
    - sane_lists

pages:
  - Home: index.md
  - Bash: bash.md
  - Quest: quest.md
  - Nextflow: nextflow.md
  - Pipelines: pipelines.md
  - R: r.md
  - Travis-CI: travis-ci.md
  - Google Cloud: google-cloud.md
  - CeNDR: cendr.md
  - Domains: domains.md
  - Andersen Labsite: labsite.md