site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - fenced_code
    - sane_lists

pages:
  - Home: index.md
  - Bash: bash.md
  - Quest:
    - Introduction: quest-intro.md
    - Setup: quest-setup.md
    - Nextflow: quest-nextflow.md
    - Mounting Quest: quest-mount.md
  - Pipelines:
    - NIL / RIL: pipeline-nil-ril.md
    - Concordance: pipeline-concordance.md
    - WI: pipeline-wi.md
    - Trimming: pipeline-trimming.md
    - Cegwas: pipeline-cegwas.md
  - R: r.md
  - Google Cloud: google-cloud.md
  - CeNDR: cendr.md
  - Andersen Labsite: labsite.md