site_name: Andersen Lab Dry Guide
theme: readthedocs
repo_url: https://github.com/Andersenlab/dry-guide


markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - fenced_code
    - sane_lists

pages:
  - Home: index.md
  - Bash: bash.md
  - Quest:
    - Introduction: quest-intro.md
    - Mounting Quest: quest-mount.md
  - Nextflow: nextflow.md
  - Pipelines:
    - umm: pipelines.md
    - NIL-Pipeline: pipeline-nil.md
  - R: r.md
  - Travis-CI: travis-ci.md
  - Google Cloud: google-cloud.md
  - CeNDR: cendr.md
  - Domains: domains.md
  - Andersen Labsite: labsite.md